CREATE PROC FI_SP_ConsClienteCPF
	@CPF VARCHAR(11)
AS
BEGIN
		SELECT NOME, SOBRENOME, CPF, NACIONALIDADE, CEP, ESTADO, CIDADE, LOGRADOURO, EMAIL, TELEFONE, ID FROM CLIENTES WITH(NOLOCK) WHERE CPF = @CPF
END